/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Airliner;
import Business.AirlinerDirectory;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author aman9
 */
public class ManageTravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTravelAgencyJPanel
     */
    JPanel travelAgencyContainer;
    AirlinerDirectory airlinerDirectory;
    
    public ManageTravelAgencyJPanel(JPanel travelAgencyContainer, AirlinerDirectory airlinerDirectory) {
        initComponents();
        this.travelAgencyContainer = travelAgencyContainer;
        this.airlinerDirectory = airlinerDirectory;
        refreshTable();
    }
    
    public void refreshTable(){
        int rowCount=airlineListJTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)airlineListJTable.getModel();
        //dtm.setRowCount(0);
        for (int i = rowCount-1; i>=0; i-- ){
            dtm.removeRow(i);
        }
        
        for (Airliner a: airlinerDirectory.getAirlineDirectory()){
            Object row[]= new Object[1];
            row[0] = a;
            //row[1]=a.getAirlineName();
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airlineListJTable = new javax.swing.JTable();
        removeBtnAirline = new javax.swing.JButton();
        addBtnAirline = new javax.swing.JButton();
        viewBtnAirline = new javax.swing.JButton();
        manageAirlineLabel = new javax.swing.JLabel();

        airlineListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "List of Airlines"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlineListJTable);

        removeBtnAirline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        removeBtnAirline.setText("Remove");
        removeBtnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnAirlineActionPerformed(evt);
            }
        });

        addBtnAirline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtnAirline.setText("Add Airliner");
        addBtnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnAirlineActionPerformed(evt);
            }
        });

        viewBtnAirline.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        viewBtnAirline.setText("View Airliner");
        viewBtnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnAirlineActionPerformed(evt);
            }
        });

        manageAirlineLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageAirlineLabel.setText("Manage Airlines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(removeBtnAirline)
                                .addGap(40, 40, 40)
                                .addComponent(addBtnAirline)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewBtnAirline))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(manageAirlineLabel)))
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(manageAirlineLabel)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtnAirline)
                    .addComponent(addBtnAirline)
                    .addComponent(viewBtnAirline))
                .addGap(263, 263, 263))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnAirlineActionPerformed
        
        CreateAirlinerJPanel cajp= new CreateAirlinerJPanel (travelAgencyContainer, airlinerDirectory);
        travelAgencyContainer.add("CreateAirlinerJPanel",cajp);
        CardLayout layout= (CardLayout)travelAgencyContainer.getLayout();
        layout.next(travelAgencyContainer);        
    }//GEN-LAST:event_addBtnAirlineActionPerformed

    private void viewBtnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnAirlineActionPerformed
        int selectedRows=airlineListJTable.getSelectedRow();
        if(selectedRows<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first" , "Warning" , JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            Airliner a=(Airliner)airlineListJTable.getValueAt(selectedRows, 0);
            ViewAirlinerJPanel vajp= new ViewAirlinerJPanel(travelAgencyContainer,a,airlinerDirectory);
            travelAgencyContainer.add("ViewAirlinerJPanel",vajp);
            CardLayout layout = (CardLayout)travelAgencyContainer.getLayout();
            layout.next(travelAgencyContainer);
        }
    }//GEN-LAST:event_viewBtnAirlineActionPerformed

    private void removeBtnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnAirlineActionPerformed
        int selectedRow=airlineListJTable.getSelectedRow();
        if (selectedRow >= 0){
            int selectionButton= JOptionPane.YES_NO_OPTION;
            int selectionResult= JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION){
                Airliner air = (Airliner)airlineListJTable.getValueAt(selectedRow, 0);
                airlinerDirectory.removeAirliner(air);
                refreshTable();
            }            
        }
        else{
                JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }//GEN-LAST:event_removeBtnAirlineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtnAirline;
    private javax.swing.JTable airlineListJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageAirlineLabel;
    private javax.swing.JButton removeBtnAirline;
    private javax.swing.JButton viewBtnAirline;
    // End of variables declaration//GEN-END:variables
}
