/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Airliner;
import Business.AirlinerDirectory;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import java.awt.Component;
/**
 *
 * @author aman9
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirliner
     */
    JPanel travelAgencyContainer;
    Airliner air;
    AirlinerDirectory airlinerDirectory;
    private int flag;
    public ViewAirlinerJPanel(JPanel travelAgencyContainer, Airliner air, AirlinerDirectory airlinerDirectory) {
        initComponents();
        this.travelAgencyContainer=travelAgencyContainer;
        this.air=air;
        this.airlinerDirectory=airlinerDirectory;
        airlineNameCreateTextField.setText(air.getAirlineName());
        headquartersTextField.setText(air.getAirHeadquarters());
        hubTextField.setText(air.getAirHub());
        airlineNameCreateTextField.setEditable(false);
        headquartersTextField.setEditable(false);
        hubTextField.setEditable(false);
        updateBtnView.setEnabled(true);
        saveBtnView.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlineViewLabel = new javax.swing.JLabel();
        airlineNameCreateLabel = new javax.swing.JLabel();
        airlineNameCreateTextField = new javax.swing.JTextField();
        backBtnView = new javax.swing.JButton();
        updateBtnView = new javax.swing.JButton();
        saveBtnView = new javax.swing.JButton();
        hubTextField = new javax.swing.JTextField();
        hubLabel = new javax.swing.JLabel();
        headquartersTextField = new javax.swing.JTextField();
        headquartersLabel = new javax.swing.JLabel();

        airlineViewLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        airlineViewLabel.setText("View Airline");

        airlineNameCreateLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        airlineNameCreateLabel.setText("Airline Name");

        backBtnView.setText("Back");
        backBtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnViewActionPerformed(evt);
            }
        });

        updateBtnView.setText("Update");
        updateBtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnViewActionPerformed(evt);
            }
        });

        saveBtnView.setText("Save");
        saveBtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnViewActionPerformed(evt);
            }
        });

        hubLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        hubLabel.setText("Hub");

        headquartersLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        headquartersLabel.setText("Headquarters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airlineNameCreateLabel)
                            .addComponent(headquartersLabel)
                            .addComponent(hubLabel))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hubTextField)
                            .addComponent(headquartersTextField)
                            .addComponent(airlineNameCreateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airlineViewLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtnView)
                                .addGap(45, 45, 45)
                                .addComponent(updateBtnView)))
                        .addGap(45, 45, 45)
                        .addComponent(saveBtnView)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(airlineViewLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlineNameCreateLabel)
                    .addComponent(airlineNameCreateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headquartersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headquartersLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hubLabel))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtnView)
                    .addComponent(updateBtnView)
                    .addComponent(saveBtnView))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnViewActionPerformed
        airlineNameCreateTextField.setEditable(true);
        headquartersTextField.setEditable(true);
        hubTextField.setEditable(true);
        updateBtnView.setEnabled(false);
        saveBtnView.setEnabled(true);
    }//GEN-LAST:event_updateBtnViewActionPerformed

    private void saveBtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnViewActionPerformed
        airlineNameCreateTextField.setEditable(false);
        headquartersTextField.setEditable(false);
        hubTextField.setEditable(false);
        updateBtnView.setEnabled(true);
        saveBtnView.setEnabled(false);
        
        flag=0;
        if(airlineNameCreateTextField.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Airline Name field cannot be empty");
            airlineNameCreateTextField.setText("");
            flag=1;
        }
        
        if(headquartersTextField.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Headquarters field cannot be empty");
            headquartersTextField.setText("");
            flag=1;
        }
        
        if(hubTextField.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Hub field cannot be empty");
            hubTextField.setText("");
            flag=1;
        }
        
        if (flag==0){
            
            air.setAirlineName(airlineNameCreateTextField.getText());
            air.setAirHeadquarters(headquartersTextField.getText());
            air.setAirHub(hubTextField.getText());
            
            JOptionPane.showMessageDialog(null, "Airline updated successfully");
        }
        else{
            JOptionPane.showMessageDialog(null, "Unable to update airline. Please enter correct values in the fields.");
        }
        
    }//GEN-LAST:event_saveBtnViewActionPerformed

    private void backBtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnViewActionPerformed
        travelAgencyContainer.remove(this);
        CardLayout layout = (CardLayout)travelAgencyContainer.getLayout();
        Component comps[]= travelAgencyContainer.getComponents();
        for (Component comp: comps){
            if (comp instanceof ManageTravelAgencyJPanel){
                ManageTravelAgencyJPanel manageTravel = (ManageTravelAgencyJPanel)comp;
                manageTravel.refreshTable();
            }
            layout.previous(travelAgencyContainer);
        }
    }//GEN-LAST:event_backBtnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlineNameCreateLabel;
    private javax.swing.JTextField airlineNameCreateTextField;
    private javax.swing.JLabel airlineViewLabel;
    private javax.swing.JButton backBtnView;
    private javax.swing.JLabel headquartersLabel;
    private javax.swing.JTextField headquartersTextField;
    private javax.swing.JLabel hubLabel;
    private javax.swing.JTextField hubTextField;
    private javax.swing.JButton saveBtnView;
    private javax.swing.JButton updateBtnView;
    // End of variables declaration//GEN-END:variables
}
