/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.AirlinerDirectory;
import Business.Airliner;
import Business.Customer;
import Business.CustomerDirectory;
import Business.FlightSchedule;
import Business.FlightScheduleDirectory;
import Business.Seat;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author aman9
 */
public class BookFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightJPanel
     */
    JPanel travelAgencyContainer;
    private AirlinerDirectory airlinerDirectory;
    private FlightSchedule flight;
    private CustomerDirectory customerDirectory;
    private Customer cust;
    private FlightScheduleDirectory flightDirectory;
    int i;
    int noOfPass;
    public BookFlightJPanel(JPanel travelAgencyContainer,AirlinerDirectory airlinerDirectory,CustomerDirectory customerDirectory, Customer cust,FlightSchedule flight) {
        initComponents();
        this.travelAgencyContainer=travelAgencyContainer;
        this.airlinerDirectory=airlinerDirectory;
        this.customerDirectory=customerDirectory;
        this.flight=flight;
        this.cust=cust;
        this.flightDirectory=flightDirectory;
        /*passportNumberTextField.setEditable(false);
        passNameTextField.setEditable(false);*/
        displaySearchData();
        /*for (int i=1; i<=customerDirectory.getCustomerDirectory().);
)
            rowSeatsComboBos.addItem(seat);
        
        for (char col='A';col<='F';col++)
            columnSeatsComboBox.addItem(col);*/
       
       // populatePassenger();
        
    }
    
    public void displaySearchData(){
        flightNumberTextField.setText(flight.getFlightNumber());
        timeOfDayTextField.setText(flight.getTimeOfDay());
        originTextField.setText(cust.getOrigin());
        destinationTextField.setText(cust.getDestination());        
        originTextField.setEditable(false);
        destinationTextField.setEditable(false);        
    }
    
    /*public void populatePassenger(){
        int noOfPass=cust.getNumberOfPassengers();
        for (i=1;i<=noOfPass;i++)
            passengerNumberComboBox.addItem(i);
    }*/

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightOrderLabel = new javax.swing.JLabel();
        flightNumberLabel = new javax.swing.JLabel();
        flightNumberTextField = new javax.swing.JTextField();
        originLabel = new javax.swing.JLabel();
        originTextField = new javax.swing.JTextField();
        destinationLabel = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        timeOfdayLabel = new javax.swing.JLabel();
        timeOfDayTextField = new javax.swing.JTextField();
        seatSelectionBtn = new javax.swing.JButton();

        flightOrderLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        flightOrderLabel.setText("Flight Order");

        flightNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        flightNumberLabel.setText("Flight Number");

        originLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        originLabel.setText("Origin");

        destinationLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        destinationLabel.setText("Destination");

        timeOfdayLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        timeOfdayLabel.setText("Time Of Day");

        seatSelectionBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        seatSelectionBtn.setText("Seat Selection");
        seatSelectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatSelectionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeOfdayLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeOfDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(destinationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(originLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flightNumberLabel)
                                .addGap(38, 38, 38)
                                .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatSelectionBtn)
                            .addComponent(flightOrderLabel))))
                .addGap(463, 463, 463))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(flightOrderLabel)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNumberLabel)
                    .addComponent(flightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLabel)
                    .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeOfdayLabel)
                    .addComponent(timeOfDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(seatSelectionBtn)
                .addGap(143, 143, 143))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seatSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatSelectionBtnActionPerformed
        // TODO add your handling code here:
        SeatSelectionJPanel ssjp= new SeatSelectionJPanel (travelAgencyContainer,cust,flight);
        travelAgencyContainer.add("SearchFlightJPanel", ssjp);
        CardLayout layout= (CardLayout)travelAgencyContainer.getLayout();
        layout.next(travelAgencyContainer);
        
        /*noOfPass=cust.getNumberOfPassengers();
        if (i<noOfPass){
            JOptionPane.showMessageDialog(null, "Please add details for all the passengers first!!", "Warning" , JOptionPane.WARNING_MESSAGE);
        }*/
        /*else{
            SeatSelectionJPanel ssjp= new SeatSelectionJPanel(travelAgencyContainer,cust,flight);
        }*/
    }//GEN-LAST:event_seatSelectionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel flightNumberLabel;
    private javax.swing.JTextField flightNumberTextField;
    private javax.swing.JLabel flightOrderLabel;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextField originTextField;
    private javax.swing.JButton seatSelectionBtn;
    private javax.swing.JTextField timeOfDayTextField;
    private javax.swing.JLabel timeOfdayLabel;
    // End of variables declaration//GEN-END:variables
}
