/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.FlightSchedule;
import Business.AirlinerDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Customer;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import Business.FlightScheduleDirectory;

/**
 *
 * @author aman9
 */
public class ManageSearchBookFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSearchBookFlightJPanel
     */
    JPanel travelAgencyContainer;
    AirlinerDirectory airlinerDirectory;
    //FlightSchedule flightSchedule;
    CustomerDirectory customerDirectory;
    FlightScheduleDirectory flightDirectory;
    int flag;
    
    public ManageSearchBookFlightJPanel(JPanel travelAgencyContainer,AirlinerDirectory airlinerDirectory, CustomerDirectory customerDirectory,FlightScheduleDirectory flightDirectory) {
        initComponents();
        this.travelAgencyContainer=travelAgencyContainer;
        this.airlinerDirectory=airlinerDirectory;
        //this.flightSchedule=flightSchedule;
        this.customerDirectory=customerDirectory;    
        this.flightDirectory=flightDirectory;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSearchBookLabel = new javax.swing.JLabel();
        searchFlightLabel = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        originTextField = new javax.swing.JTextField();
        destinationLabel = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        searchFlightsBtn = new javax.swing.JButton();
        numberOfPassLabel = new javax.swing.JLabel();
        numberOfPassTextField = new javax.swing.JTextField();

        manageSearchBookLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageSearchBookLabel.setText("Manage Search and Book Flight");

        searchFlightLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        searchFlightLabel.setText("Search Flight");

        originLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        originLabel.setText("Origin");

        originTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originTextFieldActionPerformed(evt);
            }
        });

        destinationLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        destinationLabel.setText("Destination");

        searchFlightsBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchFlightsBtn.setText("Search Flights");
        searchFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightsBtnActionPerformed(evt);
            }
        });

        numberOfPassLabel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        numberOfPassLabel.setText("Number of Passengers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(destinationLabel)
                                    .addComponent(originLabel))
                                .addGap(290, 290, 290)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(originTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(destinationTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberOfPassLabel)
                                .addGap(220, 220, 220)
                                .addComponent(numberOfPassTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchFlightsBtn)
                            .addComponent(searchFlightLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(manageSearchBookLabel)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(manageSearchBookLabel)
                .addGap(35, 35, 35)
                .addComponent(searchFlightLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originLabel)
                    .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfPassLabel)
                    .addComponent(numberOfPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(searchFlightsBtn)
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void originTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originTextFieldActionPerformed

    private void searchFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightsBtnActionPerformed
        
        flag=0;
        if(originTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Origin field cannot be empty");
            originTextField.setText("");
            flag=1;
        }
        
        if(destinationTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Destination field cannot be empty");
            destinationTextField.setText("");
            flag=1;
        }
        
        /*if(dateTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Date field cannot be empty");
            dateTextField.setText("");
            flag=1;
        }*/
        
        if (flag==0){             
            try{
                Integer.parseInt(numberOfPassTextField.getText());                
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter numeric value only for number of passengers field!!");
                return;
            }
            
            Customer cust = customerDirectory.addCustomer();
            cust.setOrigin(originTextField.getText());
            cust.setDestination(destinationTextField.getText());
            //cust.setDate(dateTextField.getText());
            cust.setNumberOfPassengers(Integer.parseInt(numberOfPassTextField.getText()));

            JOptionPane.showMessageDialog(null, "Passenger Details added successfully");
            
            SearchFlightJPanel sfjp = new SearchFlightJPanel(travelAgencyContainer,airlinerDirectory,customerDirectory,cust);
            travelAgencyContainer.add("SearchFlightJPanel", sfjp);
            CardLayout layout= (CardLayout)travelAgencyContainer.getLayout();
            layout.next(travelAgencyContainer);
            
        }
        else
            JOptionPane.showMessageDialog(null, "Unable to add passenger details. Please enter correct values in fields!!");
               
        
    }//GEN-LAST:event_searchFlightsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel manageSearchBookLabel;
    private javax.swing.JLabel numberOfPassLabel;
    private javax.swing.JTextField numberOfPassTextField;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextField originTextField;
    private javax.swing.JLabel searchFlightLabel;
    private javax.swing.JButton searchFlightsBtn;
    // End of variables declaration//GEN-END:variables
}
