/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Customer;
import Business.FlightSchedule;
import Business.Seat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.SeatDirectory;
import java.awt.CardLayout;

/**
 *
 * @author aman9
 */
public class SeatSelectionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeatSelectionJPanel
     */
    JPanel travelAgencyContainer;
    Customer cust;
    FlightSchedule flight;
    SeatDirectory seatDirectory;
    int flag;
    int seats [][];
    public SeatSelectionJPanel(JPanel travelAgencyContainer, Customer cust, FlightSchedule flight) {
        initComponents();
        this.travelAgencyContainer=travelAgencyContainer;
        this.cust=cust;
        this.flight=flight;
        seatDirectory=flight.getSeatDirectory();
        flag=0;
        rowComboBox.removeAllItems();
        for(int i=1; i<= flight.getNumberOfRows(); i++) {
           rowComboBox.addItem(i);
        }
        String[] test = new String[]{"Window","Middle", "Aisle"};
        for (String s:test)
            columnComboBox.addItem(s);
        seats = new int[flight.getNumberOfRows()+1][4];
        for(int i=1; i< (flight.getNumberOfRows()+1); i++){
            for(int j=1; j<4; j++){
                seats[i][j]=1;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatsSelectionLabel = new javax.swing.JLabel();
        rowComboBox = new javax.swing.JComboBox();
        columnSeatsLabel = new javax.swing.JLabel();
        rowSeatsLabel = new javax.swing.JLabel();
        columnComboBox = new javax.swing.JComboBox();
        availabilityBtn = new javax.swing.JButton();
        confirmBookingBtn = new javax.swing.JButton();
        viewTicketBtn = new javax.swing.JButton();

        seatsSelectionLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        seatsSelectionLabel.setText("Seats selection");

        columnSeatsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        columnSeatsLabel.setText("Column");

        rowSeatsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rowSeatsLabel.setText("Row");

        availabilityBtn.setText("Check Availability");
        availabilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availabilityBtnActionPerformed(evt);
            }
        });

        confirmBookingBtn.setText("Confirm");
        confirmBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingBtnActionPerformed(evt);
            }
        });

        viewTicketBtn.setText("View Ticket");
        viewTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(availabilityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmBookingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewTicketBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatsSelectionLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(rowSeatsLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(rowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(columnSeatsLabel)
                                    .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowSeatsLabel)
                    .addComponent(columnSeatsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsSelectionLabel)
                    .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(availabilityBtn)
                .addGap(18, 18, 18)
                .addComponent(confirmBookingBtn)
                .addGap(96, 96, 96)
                .addComponent(viewTicketBtn)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void availabilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availabilityBtnActionPerformed
        // TODO add your handling code here:
        checkAvaibility();
    }//GEN-LAST:event_availabilityBtnActionPerformed

    private void confirmBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingBtnActionPerformed
        // TODO add your handling code here:
         flag++;
        if(flag <= cust.getNumberOfPassengers())
        {
            int selectedRow = (int) rowComboBox.getSelectedItem();
            String selectedColumn = (String) columnComboBox.getSelectedItem();
            if (selectedColumn.equals("Window"))
            {
                if(seats[selectedRow][1] == 1)
                {
                    seats[selectedRow][1] = 0;
                    Seat seat = seatDirectory.addSeat();
                    seat.setCustomer(cust);
                    seat.setFlight(flight);
                    seat.setSeatNumber("Window "+selectedRow);
                    /*Seats seat = seatDirectory.addSeat();
                    seat.setCustomer(customer);
                    seat.setFlight(flight);
                    seat.setSeatNumber("Window "+ selectedRow);*/
                    JOptionPane.showMessageDialog(null,"Ticket booking confirmed!");
                }
                else
                {
               
                    JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
                }
                
            }
            if (selectedColumn.equals("Middle"))
            {
                if(seats[selectedRow][2] == 1)
                {
                    seats[selectedRow][2] = 0;
                    Seat seat = seatDirectory.addSeat();
                    seat.setCustomer(cust);
                    seat.setFlight(flight);
                    seat.setSeatNumber("Window "+selectedRow);
                    JOptionPane.showMessageDialog(null,"Ticket booking confirmed!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
                }
            }
           if (selectedColumn.equals("Aisle"))
            {
                if(seats[selectedRow][3] == 1)
                {
                    seats[selectedRow][3] = 0;
                    Seat seat = seatDirectory.addSeat();
                    seat.setCustomer(cust);
                    seat.setFlight(flight);
                    seat.setSeatNumber("Window "+selectedRow);
                    JOptionPane.showMessageDialog(null,"Ticket booking confirmed!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "You have booked your all tickets! Thank You!");
    }//GEN-LAST:event_confirmBookingBtnActionPerformed

    private void viewTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketBtnActionPerformed
        // TODO add your handling code here:
        ViewTicketJPanel vtjp=new ViewTicketJPanel(travelAgencyContainer,seatDirectory);
        travelAgencyContainer.add("ViewTicketJPanel", vtjp);
        CardLayout layout= (CardLayout)travelAgencyContainer.getLayout();
        layout.next(travelAgencyContainer);
    }//GEN-LAST:event_viewTicketBtnActionPerformed

    public void checkAvaibility(){
        int selectedRow = (int) rowComboBox.getSelectedItem();
        String selectedColumn = (String) columnComboBox.getSelectedItem();
        if (selectedColumn.equals("Window"))
        {
            if(seats[selectedRow][1] == 1)
            {
                JOptionPane.showMessageDialog(null,"Available!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
            }
                
        }
        if (selectedColumn.equals("Middle"))
        {
             if(seats[selectedRow][2] == 1)
            {
                JOptionPane.showMessageDialog(null,"Available!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
            }
        }
        if (selectedColumn.equals("Aisle"))
        {
             if(seats[selectedRow][3] == 1)
            {
                JOptionPane.showMessageDialog(null,"Available!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Not Available! please Select another seat");
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availabilityBtn;
    private javax.swing.JComboBox columnComboBox;
    private javax.swing.JLabel columnSeatsLabel;
    private javax.swing.JButton confirmBookingBtn;
    private javax.swing.JComboBox rowComboBox;
    private javax.swing.JLabel rowSeatsLabel;
    private javax.swing.JLabel seatsSelectionLabel;
    private javax.swing.JButton viewTicketBtn;
    // End of variables declaration//GEN-END:variables
}
